/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebook.mainFrame;

import com.ebooks.dao.TacGiaDAO;
import com.ebooks.dao.TacGia_SachDAO;
import com.ebooks.dao.TheLoaiDAO;
import com.ebooks.dao.TheLoai_SachDAO;
import com.ebooks.helper.DialogHelper;
import com.ebooks.helper.MovingForm;
import com.ebooks.helper.ShareHelper;
import com.ebooks.model.Sach;
import com.ebooks.model.TacGia;
import com.ebooks.model.TacGia_Sach;
import com.ebooks.model.TheLoai;
import com.ebooks.model.TheLoai_Sach;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thinh
 */
public class AddTypeAndAuthorDiaLog extends javax.swing.JDialog {

    static public Sach sachSeletion = new Sach();
    static public TheLoai theLoaiSeletion = new TheLoai();
    static public TacGia tacGiaSeletion = new TacGia();

    private TheLoai_SachDAO DAOTL_S = new TheLoai_SachDAO();
    private TacGia_SachDAO DAOTG_S = new TacGia_SachDAO();
    public AddTypeAndAuthorDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        MovingForm.initMoving(this, pnlTypeAndAuthor);
        setBackground(new Color(0, 0, 0, 0));
    }

    private void setFormSach(Sach sach) {
        txtMaSach.setText(sach.getMaSach());
        txtDuongDan.setText(sach.getDuongDan());
        txtNhaXuatBan.setText(sach.getMaNXB());
        txtTenSach.setText(sach.getTenSach());
        lblSachImg.setIcon(ShowImg(sach.getBiaTruoc()));
    }

    private ImageIcon ShowImg(String nameImg) {
        ImageIcon imgIcon = new ImageIcon("..\\DuAn01-ebookLibrary-project\\src\\main\\java\\com\\ebooks\\imgEbooks\\" + nameImg);
        Image image = imgIcon.getImage();
        Image newimg = image.getScaledInstance(160, 160, java.awt.Image.SCALE_SMOOTH);
        imgIcon = new ImageIcon(newimg);
        return imgIcon;
    }

    private String ConventTypeBook(String maTheLoai) {
        TheLoaiDAO DAOTL = new TheLoaiDAO();
        TheLoai theLoai = DAOTL.findById(maTheLoai);
        return theLoai.getTenTheLoai();
    }
    
    private String ConventAuthorBook(String maTacGia) {
        TacGiaDAO DAOTG = new TacGiaDAO();
        TacGia tacGia = DAOTG.findById(maTacGia);
        return tacGia.getHoTen();
    }

//------------------------------------LẤY DƯ LIỆU VÀ HIỂN THI------------------------------------//
    private void fillTableTypeAndBook() {
        List<TheLoai_Sach> ListTL_S = new ArrayList<TheLoai_Sach>();
        DefaultTableModel model;
        model = (DefaultTableModel) tblTheLoai.getModel();
        tblTheLoai.setSelectionBackground(new Color(87, 190, 110));
        model.setRowCount(0);
        try {
            ListTL_S = DAOTL_S.selectAllBook(txtMaSach.getText());
            for (TheLoai_Sach loai_Sach : ListTL_S) {
                Object[] row = {loai_Sach.getMaTheLoai(), loai_Sach.getMaSach(), ConventTypeBook(loai_Sach.getMaTheLoai())};
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void fillTableAuthorAndBook() {
        List<TacGia_Sach> ListTG_S = new ArrayList<TacGia_Sach>();
        DefaultTableModel model;
        model = (DefaultTableModel) tblTacGia.getModel();
        tblTacGia.setSelectionBackground(new Color(87, 190, 110));
        model.setRowCount(0);
        try {
            ListTG_S = DAOTG_S.selectAllBook(txtMaSach.getText());
            for (TacGia_Sach tacGia_Sach : ListTG_S) {
                Object[] row = {tacGia_Sach.getMaTacGia(),tacGia_Sach.getMaSach(),ConventAuthorBook(tacGia_Sach.getMaTacGia())};
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTypeAndAuthor = new com.ebooks.Compoment.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlAddInfo = new com.ebooks.Compoment.PanelRound();
        txtMaSach = new javax.swing.JTextField();
        txtNhaXuatBan = new javax.swing.JTextField();
        lblSachImg = new com.ebooks.Compoment.ImageBoder();
        lblMaSach = new javax.swing.JLabel();
        lblTenSach1 = new javax.swing.JLabel();
        btnChonSach = new com.ebooks.Compoment.MyButton();
        txtDuongDan = new javax.swing.JTextField();
        lblTenSach2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTheLoai = new com.ebooks.Compoment.Table();
        lblTenSach3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTacGia = new com.ebooks.Compoment.Table();
        lblTenSach4 = new javax.swing.JLabel();
        btnHuyBoTheLoai = new com.ebooks.Compoment.MyButton();
        btnThemTheLoai = new com.ebooks.Compoment.MyButton();
        btnThemTacGia = new com.ebooks.Compoment.MyButton();
        btnHuyBoTacGia = new com.ebooks.Compoment.MyButton();
        jPanel1 = new javax.swing.JPanel();
        txtTenSach = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnlExit2 = new com.ebooks.Compoment.PanelRound();
        lblExit2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlTypeAndAuthor.setBackground(new java.awt.Color(254, 254, 254));
        pnlTypeAndAuthor.setPreferredSize(new java.awt.Dimension(910, 550));
        pnlTypeAndAuthor.setRoundBottomLeft(20);
        pnlTypeAndAuthor.setRoundBottomRight(20);
        pnlTypeAndAuthor.setRoundTopLeft(20);
        pnlTypeAndAuthor.setRoundTopRight(20);
        pnlTypeAndAuthor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        pnlTypeAndAuthor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setBorder(null);

        pnlAddInfo.setBackground(new java.awt.Color(249, 249, 249));
        pnlAddInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaSach.setEditable(false);
        txtMaSach.setBackground(new java.awt.Color(222, 247, 227));
        pnlAddInfo.add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 260, 40));

        txtNhaXuatBan.setEditable(false);
        txtNhaXuatBan.setBackground(new java.awt.Color(222, 247, 227));
        pnlAddInfo.add(txtNhaXuatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 260, 40));

        lblSachImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/stock-photo-76398531.jpg"))); // NOI18N
        lblSachImg.setRadius(20);
        pnlAddInfo.add(lblSachImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 200));

        lblMaSach.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaSach.setText("Mã Sách");
        pnlAddInfo.add(lblMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        lblTenSach1.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach1.setText("Tên Sách");
        pnlAddInfo.add(lblTenSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        btnChonSach.setBackground(new java.awt.Color(87, 190, 110));
        btnChonSach.setForeground(new java.awt.Color(255, 255, 255));
        btnChonSach.setText("Chọn Sách");
        btnChonSach.setBoderColor(new java.awt.Color(87, 190, 110));
        btnChonSach.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnChonSach.setRadius(10);
        btnChonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonSachActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnChonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 200, 40));

        txtDuongDan.setEditable(false);
        txtDuongDan.setBackground(new java.awt.Color(222, 247, 227));
        pnlAddInfo.add(txtDuongDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 260, 40));

        lblTenSach2.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach2.setText("Thể loại của sách");
        pnlAddInfo.add(lblTenSach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel3.setText("Mã Nhà Xuẩt Bản");
        pnlAddInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        tblTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã thể loại", "Mã sách", "Tên thể loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTheLoai.setSelectionBackground(new java.awt.Color(87, 190, 110));
        tblTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTheLoaiMouseClicked(evt);
            }
        });
        tblTheLoai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblTheLoaiPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblTheLoai);

        pnlAddInfo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 390, 190));

        lblTenSach3.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach3.setText("File PDF");
        pnlAddInfo.add(lblTenSach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        tblTacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã tác giả", "Mã sách", "Tên tác giả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTacGia.setSelectionBackground(new java.awt.Color(87, 190, 110));
        tblTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTacGiaMouseClicked(evt);
            }
        });
        tblTacGia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblTacGiaPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tblTacGia);

        pnlAddInfo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 390, 190));

        lblTenSach4.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach4.setText("Tác giả của sách");
        pnlAddInfo.add(lblTenSach4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        btnHuyBoTheLoai.setBackground(new java.awt.Color(255, 102, 102));
        btnHuyBoTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyBoTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/circle-cross.png"))); // NOI18N
        btnHuyBoTheLoai.setText("Hủy bỏ");
        btnHuyBoTheLoai.setBoderColor(new java.awt.Color(255, 102, 102));
        btnHuyBoTheLoai.setEnabled(false);
        btnHuyBoTheLoai.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnHuyBoTheLoai.setRadius(10);
        btnHuyBoTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoTheLoaiActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnHuyBoTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 110, 40));

        btnThemTheLoai.setBackground(new java.awt.Color(87, 190, 110));
        btnThemTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/add-document.png"))); // NOI18N
        btnThemTheLoai.setText("Thêm thể loại");
        btnThemTheLoai.setBoderColor(new java.awt.Color(87, 190, 110));
        btnThemTheLoai.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnThemTheLoai.setRadius(10);
        btnThemTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTheLoaiActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnThemTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 160, 40));

        btnThemTacGia.setBackground(new java.awt.Color(87, 190, 110));
        btnThemTacGia.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/user-add (1).png"))); // NOI18N
        btnThemTacGia.setText("Tác giả");
        btnThemTacGia.setBoderColor(new java.awt.Color(87, 190, 110));
        btnThemTacGia.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnThemTacGia.setRadius(10);
        btnThemTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTacGiaActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnThemTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 160, 40));

        btnHuyBoTacGia.setBackground(new java.awt.Color(255, 102, 102));
        btnHuyBoTacGia.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyBoTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/circle-cross.png"))); // NOI18N
        btnHuyBoTacGia.setText("Hủy bỏ");
        btnHuyBoTacGia.setBoderColor(new java.awt.Color(255, 102, 102));
        btnHuyBoTacGia.setEnabled(false);
        btnHuyBoTacGia.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnHuyBoTacGia.setRadius(10);
        btnHuyBoTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoTacGiaActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnHuyBoTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 110, 40));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlAddInfo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, 10));

        txtTenSach.setEditable(false);
        txtTenSach.setBackground(new java.awt.Color(222, 247, 227));
        pnlAddInfo.add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 260, 40));

        jScrollPane1.setViewportView(pnlAddInfo);

        pnlTypeAndAuthor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 910, 440));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlTypeAndAuthor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        pnlExit2.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit2.setRoundBottomLeft(20);
        pnlExit2.setRoundTopRight(20);
        pnlExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit2MouseExited(evt);
            }
        });
        pnlExit2.setLayout(new java.awt.GridBagLayout());

        lblExit2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit2.setForeground(new java.awt.Color(255, 255, 255));
        lblExit2.setText("X");
        lblExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit2MouseClicked(evt);
            }
        });
        pnlExit2.add(lblExit2, new java.awt.GridBagConstraints());

        pnlTypeAndAuthor.add(pnlExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTypeAndAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTypeAndAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonSachActionPerformed
        new ListBookDiaLog(this, true).setVisible(true);
        setFormSach(sachSeletion);
        fillTableTypeAndBook();
        fillTableAuthorAndBook();
        return;
    }//GEN-LAST:event_btnChonSachActionPerformed

    private void btnHuyBoTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoTheLoaiActionPerformed
        int index = tblTheLoai.getSelectedRow();
        if (index != -1) {
            String maTheLoai = String.valueOf(tblTheLoai.getValueAt(index, 0));
            try {
                boolean result = DialogHelper.confirm(this, "Bạn muốn hủy thể loại này ra khổi sách");
                if (result) {
                    DAOTL_S.delete(new TheLoai_Sach(maTheLoai, txtMaSach.getText()));
                    DialogHelper.alert(this, "Hủy thành công");
                    fillTableTypeAndBook();
                    btnHuyBoTheLoai.setEnabled(false);
                    return;
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            DialogHelper.alert(this, "Hãy chọn thể loại muốn xóa!");
        }

    }//GEN-LAST:event_btnHuyBoTheLoaiActionPerformed

    private void btnThemTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTheLoaiActionPerformed
        new ListTypeBookDiaLog(this, true).setVisible(true);
        if (theLoaiSeletion != null) {
            try {
                TheLoai_Sach loai_Sach = new TheLoai_Sach();
                loai_Sach.setMaSach(txtMaSach.getText());
                loai_Sach.setMaTheLoai(theLoaiSeletion.getMaTheLoai());
                DAOTL_S.insert(loai_Sach);
                DialogHelper.alert(this, "Thêm thể loại thành công");
                fillTableTypeAndBook();
                theLoaiSeletion = null;
                return;
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnThemTheLoaiActionPerformed

    private void btnThemTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTacGiaActionPerformed
        new ListAuthorDiaLog(this, true).setVisible(true);
        if (tacGiaSeletion != null) {
            try {
                TacGia_Sach tacGia_Sach = new TacGia_Sach();
                tacGia_Sach.setMaSach(txtMaSach.getText());
                tacGia_Sach.setMaTacGia(tacGiaSeletion.getMaTacGia());
                DAOTG_S.insert(tacGia_Sach);
                DialogHelper.alert(this, "Thêm tác giả thành công");
                fillTableAuthorAndBook();
                tacGiaSeletion = null;
                return;
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnThemTacGiaActionPerformed

    private void btnHuyBoTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoTacGiaActionPerformed
        int index = tblTacGia.getSelectedRow();
        if (index != -1) {
            String maTacGia = String.valueOf(tblTacGia.getValueAt(index, 0));
            try {
                boolean result = DialogHelper.confirm(this, "Bạn muốn hủy tác giả này ra khỏi sách");
                if (result) {
                    DAOTG_S.delete(new TacGia_Sach(maTacGia, txtMaSach.getText()));
                    DialogHelper.alert(this, "Hủy thành công");
                    fillTableAuthorAndBook();
                    btnHuyBoTacGia.setEnabled(false);
                    return;
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            DialogHelper.alert(this, "Hãy chọn thể loại muốn xóa!");
        }
    }//GEN-LAST:event_btnHuyBoTacGiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTheLoaiMouseClicked
        btnHuyBoTheLoai.setEnabled(true);
    }//GEN-LAST:event_tblTheLoaiMouseClicked

    private void tblTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTacGiaMouseClicked
        btnHuyBoTheLoai.setEnabled(true);
    }//GEN-LAST:event_tblTacGiaMouseClicked

    private void lblExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblExit2MouseClicked

    private void pnlExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit2MouseClicked
        this.dispose();
    }//GEN-LAST:event_pnlExit2MouseClicked

    private void pnlExit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit2MouseEntered
        pnlExit2.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_pnlExit2MouseEntered

    private void pnlExit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit2MouseExited
        pnlExit2.setBackground(new Color(253, 127, 127));
    }//GEN-LAST:event_pnlExit2MouseExited

    private void tblTheLoaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblTheLoaiPropertyChange
        fillTableTypeAndBook();
    }//GEN-LAST:event_tblTheLoaiPropertyChange

    private void tblTacGiaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblTacGiaPropertyChange
      fillTableAuthorAndBook();
    }//GEN-LAST:event_tblTacGiaPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTypeAndAuthorDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTypeAndAuthorDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTypeAndAuthorDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTypeAndAuthorDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddTypeAndAuthorDiaLog dialog = new AddTypeAndAuthorDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.MyButton btnChonSach;
    private com.ebooks.Compoment.MyButton btnHuyBoTacGia;
    private com.ebooks.Compoment.MyButton btnHuyBoTheLoai;
    private com.ebooks.Compoment.MyButton btnThemTacGia;
    private com.ebooks.Compoment.MyButton btnThemTheLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblExit2;
    private javax.swing.JLabel lblMaSach;
    private com.ebooks.Compoment.ImageBoder lblSachImg;
    private javax.swing.JLabel lblTenSach1;
    private javax.swing.JLabel lblTenSach2;
    private javax.swing.JLabel lblTenSach3;
    private javax.swing.JLabel lblTenSach4;
    private com.ebooks.Compoment.PanelRound pnlAddInfo;
    private com.ebooks.Compoment.PanelRound pnlExit2;
    private com.ebooks.Compoment.PanelRound pnlTypeAndAuthor;
    private com.ebooks.Compoment.Table tblTacGia;
    private com.ebooks.Compoment.Table tblTheLoai;
    private javax.swing.JTextField txtDuongDan;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNhaXuatBan;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
