/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ebook.mainFrame;

import com.ebooks.dao.ThongTinNguoiDungDAO;
import com.ebooks.helper.MovingForm;
import com.ebooks.helper.ShareHelper;
import com.ebooks.model.ThongTinNguoiDung;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Thinh
 */
public class mainFrame extends javax.swing.JFrame {

    private String UrlImg = "..//DuAn01-ebookLibrary-project//src//main//java//com//ebooks//Image//";
    ThongTinNguoiDungDAO DAOTTND = new ThongTinNguoiDungDAO();

    public mainFrame() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        lblLogo.setBackground(new Color(0, 0, 0, 0));
        init();
        MovingForm.initMoving(this, pnlHeader);
        setPhanQuyen();

    }

    public void init() {
        //Set icon, show from
        setIconImage(ShareHelper.APP_ICON);
        new StartUpDiaLog(this, true).setVisible(true);
        new LogInDiaLog(this, true).setVisible(true);
    }

    public void fillTableMuonSach() {

    }

    public void setPhanQuyen() {
        if (!ShareHelper.USER.isVaiTro()) {
            mnThongTinSach.setVisible(false);
            mnQuanLySach.setVisible(false);
            mnQuanLyTaiKhoan.setVisible(false);
        } else {
            lblBanMuonSach.setVisible(false);
            tblBangMuonSach.setVisible(false);
        }
    }

    public ImageIcon ShowImg(String nameImg) {
        ImageIcon imgIcon = new ImageIcon(UrlImg + nameImg);
        Image image = imgIcon.getImage();
        Image newimg = image.getScaledInstance(160, 160, java.awt.Image.SCALE_SMOOTH);
        imgIcon = new ImageIcon(newimg);
        return imgIcon;
    }

    public void setImgAvata() {
        ThongTinNguoiDung ttnd = DAOTTND.findByIdND(ShareHelper.USER.getTenDangNhap());
        if (ttnd != null) {
            lblAvata.setIcon(ShowImg(ttnd.getAnhDaiDien()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        panelRadius1 = new com.ebooks.Compoment.PanelRadius();
        pnlHeader = new com.ebooks.Compoment.PanelRound();
        lblAvata = new com.ebooks.Compoment.ImageAvatar();
        btnSearch = new com.ebooks.Compoment.MyButton();
        lblLogo = new com.ebooks.Compoment.LabelBoder();
        lblTime1 = new javax.swing.JLabel();
        btnTurnOff = new com.ebooks.Compoment.MyButton();
        panelRadius4 = new com.ebooks.Compoment.PanelRadius();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblBanMuonSach = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBangMuonSach = new com.ebooks.Compoment.Table();
        panelRound1 = new com.ebooks.Compoment.PanelRound();
        lblTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCaiDat = new javax.swing.JMenu();
        mnitemDangXuat = new javax.swing.JMenuItem();
        mnTaiKhoan = new javax.swing.JMenu();
        mnitemDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnQuanLyTaiKhoan = new javax.swing.JMenuItem();
        mnThongTinSach = new javax.swing.JMenu();
        mnitemNXB = new javax.swing.JMenuItem();
        mnitemTheLoai = new javax.swing.JMenuItem();
        mnitemTacGia = new javax.swing.JMenuItem();
        mnQuanLySach = new javax.swing.JMenu();
        mnitemSach = new javax.swing.JMenuItem();
        mnitemQuanLyChiTietSach = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnitemMuonSach = new javax.swing.JMenuItem();
        mnDocSach = new javax.swing.JMenu();
        mnitemLichSuMS = new javax.swing.JMenuItem();
        mnitemMuonSach1 = new javax.swing.JMenuItem();
        mnMuonSach = new javax.swing.JMenu();
        mnitemTroGiup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRadius1.setBackground(new java.awt.Color(250, 250, 250));
        panelRadius1.setRadius(20);
        panelRadius1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(205, 245, 217));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/41b92ec3eab97e4c24b3f6e8fe75ddec.png"))); // NOI18N
        lblAvata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAvataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAvataMouseExited(evt);
            }
        });
        lblAvata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlHeader.add(lblAvata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 60, 60));

        btnSearch.setBackground(new java.awt.Color(149, 219, 170));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/search (1).png"))); // NOI18N
        btnSearch.setBoderColor(new java.awt.Color(205, 239, 215));
        btnSearch.setColorClick(new java.awt.Color(255, 102, 102));
        btnSearch.setColorOver(new java.awt.Color(255, 102, 102));
        btnSearch.setRadius(10);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlHeader.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 40, 40));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        lblLogo.setRadius(20);
        pnlHeader.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, 50));

        lblTime1.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        lblTime1.setText("22 : 30 CH");
        pnlHeader.add(lblTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        btnTurnOff.setBackground(new java.awt.Color(149, 219, 170));
        btnTurnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/power.png"))); // NOI18N
        btnTurnOff.setBoderColor(new java.awt.Color(205, 239, 215));
        btnTurnOff.setColorClick(new java.awt.Color(255, 102, 102));
        btnTurnOff.setColorOver(new java.awt.Color(255, 102, 102));
        btnTurnOff.setRadius(10);
        btnTurnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTurnOffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTurnOffMouseExited(evt);
            }
        });
        btnTurnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnOffActionPerformed(evt);
            }
        });
        pnlHeader.add(btnTurnOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 40, 40));

        panelRadius1.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 80));

        panelRadius4.setBackground(new java.awt.Color(205, 239, 215));
        panelRadius4.setRadius(20);
        panelRadius4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Inter SemiBold", 0, 36)); // NOI18N
        jLabel34.setText("NERDS");
        panelRadius4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel35.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        jLabel35.setText("Học tập là ánh mắt của tri thức ");
        panelRadius4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/13.png"))); // NOI18N
        panelRadius4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 300, 150));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/181-removebg-preview.png"))); // NOI18N
        panelRadius4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        panelRadius1.add(panelRadius4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1080, 170));

        lblBanMuonSach.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBanMuonSach.setText("Bảng Mượn Sách");
        panelRadius1.add(lblBanMuonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        tblBangMuonSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBangMuonSach);

        panelRadius1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 1070, 210));

        panelRound1.setBackground(new java.awt.Color(205, 245, 217));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTime.setText("sat 17/03/2023");
        panelRound1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel2.setText("Hệ thống quản lý thư viện online");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelRadius1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1120, 40));

        getContentPane().add(panelRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 610));

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 0));

        mnCaiDat.setText("Cài đặt");

        mnitemDangXuat.setText("Đăng xuất");
        mnitemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemDangXuatActionPerformed(evt);
            }
        });
        mnCaiDat.add(mnitemDangXuat);

        jMenuBar1.add(mnCaiDat);

        mnTaiKhoan.setText("Tài khoản");

        mnitemDoiMatKhau.setText("Đổi mật khẩu");
        mnitemDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemDoiMatKhauActionPerformed(evt);
            }
        });
        mnTaiKhoan.add(mnitemDoiMatKhau);
        mnTaiKhoan.add(jSeparator1);

        mnQuanLyTaiKhoan.setText("Quản lý tài khoản");
        mnQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuanLyTaiKhoanActionPerformed(evt);
            }
        });
        mnTaiKhoan.add(mnQuanLyTaiKhoan);

        jMenuBar1.add(mnTaiKhoan);

        mnThongTinSach.setText("Thông tin sách");

        mnitemNXB.setText("Quản lý nhà xuất bản");
        mnitemNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemNXBActionPerformed(evt);
            }
        });
        mnThongTinSach.add(mnitemNXB);

        mnitemTheLoai.setText("Quản lý thể loại ");
        mnitemTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemTheLoaiActionPerformed(evt);
            }
        });
        mnThongTinSach.add(mnitemTheLoai);

        mnitemTacGia.setText("Quản lý tác giả");
        mnitemTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemTacGiaActionPerformed(evt);
            }
        });
        mnThongTinSach.add(mnitemTacGia);

        jMenuBar1.add(mnThongTinSach);

        mnQuanLySach.setText("Quản lý Sách");

        mnitemSach.setText("Quản lý sách");
        mnitemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemSachActionPerformed(evt);
            }
        });
        mnQuanLySach.add(mnitemSach);

        mnitemQuanLyChiTietSach.setText("Quản lý chi tiết sách");
        mnitemQuanLyChiTietSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemQuanLyChiTietSachActionPerformed(evt);
            }
        });
        mnQuanLySach.add(mnitemQuanLyChiTietSach);
        mnQuanLySach.add(jSeparator2);

        mnitemMuonSach.setText("Quản lý mượn sách");
        mnitemMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemMuonSachActionPerformed(evt);
            }
        });
        mnQuanLySach.add(mnitemMuonSach);

        jMenuBar1.add(mnQuanLySach);

        mnDocSach.setText("Đọc sách");

        mnitemLichSuMS.setText("Lịch sử mượn sách");
        mnitemLichSuMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemLichSuMSActionPerformed(evt);
            }
        });
        mnDocSach.add(mnitemLichSuMS);

        mnitemMuonSach1.setText("Quản lý sách đã mượn");
        mnitemMuonSach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemMuonSach1ActionPerformed(evt);
            }
        });
        mnDocSach.add(mnitemMuonSach1);

        jMenuBar1.add(mnDocSach);

        mnMuonSach.setText("trợ giúp");

        mnitemTroGiup.setText("Trợ giúp");
        mnMuonSach.add(mnitemTroGiup);

        jMenuBar1.add(mnMuonSach);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        new SearchBookDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void lblAvataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvataMouseClicked
        new ProfileDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblAvataMouseClicked

    private void mnitemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemDangXuatActionPerformed
        this.setVisible(false);
        new LogInDiaLog(this, true).setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_mnitemDangXuatActionPerformed

    private void mnitemDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemDoiMatKhauActionPerformed
        new AccoutUserDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnitemDoiMatKhauActionPerformed

    private void mnQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuanLyTaiKhoanActionPerformed
        new AccoutAdmainDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnQuanLyTaiKhoanActionPerformed

    private void mnitemNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemNXBActionPerformed
        new PublishingCompanyDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnitemNXBActionPerformed

    private void mnitemTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemTheLoaiActionPerformed
        new TypeBookDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnitemTheLoaiActionPerformed

    private void mnitemTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemTacGiaActionPerformed
        new AuthorDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnitemTacGiaActionPerformed

    private void mnitemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemSachActionPerformed
        new BookDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnitemSachActionPerformed

    private void mnitemQuanLyChiTietSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemQuanLyChiTietSachActionPerformed
        new AddTypeAndAuthorDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnitemQuanLyChiTietSachActionPerformed

    private void mnitemMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemMuonSachActionPerformed

    }//GEN-LAST:event_mnitemMuonSachActionPerformed

    private void mnitemLichSuMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemLichSuMSActionPerformed
        new HistoryBorrowBookDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnitemLichSuMSActionPerformed

    private void btnTurnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnOffActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnTurnOffActionPerformed

    private void mnitemMuonSach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemMuonSach1ActionPerformed
        new BorrowedBooksDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_mnitemMuonSach1ActionPerformed

    private void btnTurnOffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnOffMouseEntered
        btnTurnOff.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_btnTurnOffMouseEntered

    private void btnTurnOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnOffMouseExited
        btnTurnOff.setBackground(new Color(149, 219, 170));
    }//GEN-LAST:event_btnTurnOffMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        btnSearch.setBackground(new Color(68, 152, 87));
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
         btnSearch.setBackground(new Color(149, 219, 170));
    }//GEN-LAST:event_btnSearchMouseExited

    private void lblAvataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvataMouseEntered
        lblAvata.setBorder(new LineBorder(new  Color(87, 170, 100), 2, true));
    }//GEN-LAST:event_lblAvataMouseEntered

    private void lblAvataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvataMouseExited
        lblAvata.setBorder(new LineBorder(new  Color(87, 170, 100), 0, true));
    }//GEN-LAST:event_lblAvataMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.MyButton btnSearch;
    private com.ebooks.Compoment.MyButton btnTurnOff;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private com.ebooks.Compoment.ImageAvatar lblAvata;
    private javax.swing.JLabel lblBanMuonSach;
    private com.ebooks.Compoment.LabelBoder lblLogo;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JMenu mnCaiDat;
    private javax.swing.JMenu mnDocSach;
    private javax.swing.JMenu mnMuonSach;
    private javax.swing.JMenu mnQuanLySach;
    private javax.swing.JMenuItem mnQuanLyTaiKhoan;
    private javax.swing.JMenu mnTaiKhoan;
    private javax.swing.JMenu mnThongTinSach;
    private javax.swing.JMenuItem mnitemDangXuat;
    private javax.swing.JMenuItem mnitemDoiMatKhau;
    private javax.swing.JMenuItem mnitemLichSuMS;
    private javax.swing.JMenuItem mnitemMuonSach;
    private javax.swing.JMenuItem mnitemMuonSach1;
    private javax.swing.JMenuItem mnitemNXB;
    private javax.swing.JMenuItem mnitemQuanLyChiTietSach;
    private javax.swing.JMenuItem mnitemSach;
    private javax.swing.JMenuItem mnitemTacGia;
    private javax.swing.JMenuItem mnitemTheLoai;
    private javax.swing.JMenuItem mnitemTroGiup;
    private com.ebooks.Compoment.PanelRadius panelRadius1;
    private com.ebooks.Compoment.PanelRadius panelRadius4;
    private com.ebooks.Compoment.PanelRound panelRound1;
    private com.ebooks.Compoment.PanelRound pnlHeader;
    private com.ebooks.Compoment.Table tblBangMuonSach;
    // End of variables declaration//GEN-END:variables
}
