/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebook.mainFrame;

import com.ebooks.helper.ShareHelper;
import java.awt.event.KeyEvent;

/**
 *
 * @author Thinh
 */
public class ManagerBorrowDiaLog extends javax.swing.JDialog {

    boolean congTac = false;
    public ManagerBorrowDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.ebooks.Compoment.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        tabTacGia = new javax.swing.JTabbedPane();
        panelRound2 = new com.ebooks.Compoment.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTacGia = new com.ebooks.Compoment.Table();
        btnLast = new com.ebooks.Compoment.MyButton();
        btnNext = new com.ebooks.Compoment.MyButton();
        btnPrev = new com.ebooks.Compoment.MyButton();
        btnFirst = new com.ebooks.Compoment.MyButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        panelRound3 = new com.ebooks.Compoment.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTacGia1 = new com.ebooks.Compoment.Table();
        btnFirst1 = new com.ebooks.Compoment.MyButton();
        btnPrev1 = new com.ebooks.Compoment.MyButton();
        btnNext1 = new com.ebooks.Compoment.MyButton();
        btnLast1 = new com.ebooks.Compoment.MyButton();
        panelRound4 = new com.ebooks.Compoment.PanelRound();
        txtTimTacGia = new com.ebooks.Compoment.SearchText();
        btnTimTacGia = new com.ebooks.Compoment.MyButton();
        panelRound5 = new com.ebooks.Compoment.PanelRound();
        txtTenDangNhap = new javax.swing.JTextField();
        lblTenDangNhap = new javax.swing.JLabel();
        txtTenDangNhap1 = new javax.swing.JTextField();
        lblTenDangNhap1 = new javax.swing.JLabel();
        txtNgaySinhTacGia = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        Calendar = new com.toedter.calendar.JCalendar();
        btnIconCld1 = new com.ebooks.Compoment.MyButton();
        txtTenDangNhap2 = new javax.swing.JTextField();
        lblTenDangNhap2 = new javax.swing.JLabel();
        txtTenDangNhap3 = new javax.swing.JTextField();
        lblTenDangNhap3 = new javax.swing.JLabel();
        txtTenDangNhap4 = new javax.swing.JTextField();
        lblTenDangNhap4 = new javax.swing.JLabel();
        myButton1 = new com.ebooks.Compoment.MyButton();
        myButton2 = new com.ebooks.Compoment.MyButton();
        myButton3 = new com.ebooks.Compoment.MyButton();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRound1.setBackground(new java.awt.Color(254, 254, 254));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tabTacGia.setBackground(new java.awt.Color(255, 255, 255));
        tabTacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabTacGia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabTacGiaStateChanged(evt);
            }
        });

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã tác giả", "Họ tên", "Ngày sinh", "Giới tính", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTacGia.setSelectionBackground(new java.awt.Color(87, 190, 110));
        tblTacGia.getTableHeader().setReorderingAllowed(false);
        tblTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTacGiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTacGia);

        panelRound2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 850, 290));

        btnLast.setBackground(new java.awt.Color(145, 227, 168));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-right.png"))); // NOI18N
        btnLast.setBoderColor(new java.awt.Color(145, 227, 168));
        btnLast.setRadius(10);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        panelRound2.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 60, 40));

        btnNext.setBackground(new java.awt.Color(145, 227, 168));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-right.png"))); // NOI18N
        btnNext.setBoderColor(new java.awt.Color(145, 227, 168));
        btnNext.setRadius(10);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        panelRound2.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 60, 40));

        btnPrev.setBackground(new java.awt.Color(145, 227, 168));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-left.png"))); // NOI18N
        btnPrev.setBoderColor(new java.awt.Color(145, 227, 168));
        btnPrev.setRadius(10);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        panelRound2.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 40));

        btnFirst.setBackground(new java.awt.Color(145, 227, 168));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-left.png"))); // NOI18N
        btnFirst.setBoderColor(new java.awt.Color(145, 227, 168));
        btnFirst.setRadius(10);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        panelRound2.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 60, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelRound2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 270, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Theo thể loại");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelRound2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 10, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Theo tác giả");
        panelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelRound2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 270, 40));

        tabTacGia.addTab("Phân loại", panelRound2);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTacGia1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã tác giả", "Họ tên", "Ngày sinh", "Giới tính", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTacGia1.setSelectionBackground(new java.awt.Color(87, 190, 110));
        tblTacGia1.getTableHeader().setReorderingAllowed(false);
        tblTacGia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTacGia1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTacGia1);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 850, 290));

        btnFirst1.setBackground(new java.awt.Color(145, 227, 168));
        btnFirst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-left.png"))); // NOI18N
        btnFirst1.setBoderColor(new java.awt.Color(145, 227, 168));
        btnFirst1.setRadius(10);
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnFirst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 60, 40));

        btnPrev1.setBackground(new java.awt.Color(145, 227, 168));
        btnPrev1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-left.png"))); // NOI18N
        btnPrev1.setBoderColor(new java.awt.Color(145, 227, 168));
        btnPrev1.setRadius(10);
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 40));

        btnNext1.setBackground(new java.awt.Color(145, 227, 168));
        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-right.png"))); // NOI18N
        btnNext1.setBoderColor(new java.awt.Color(145, 227, 168));
        btnNext1.setRadius(10);
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 60, 40));

        btnLast1.setBackground(new java.awt.Color(145, 227, 168));
        btnLast1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-right.png"))); // NOI18N
        btnLast1.setBoderColor(new java.awt.Color(145, 227, 168));
        btnLast1.setRadius(10);
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 60, 40));

        panelRound4.setBackground(new java.awt.Color(232, 244, 234));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimTacGia.setBackground(new java.awt.Color(232, 244, 234));
        txtTimTacGia.setForeground(new java.awt.Color(51, 51, 51));
        txtTimTacGia.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        txtTimTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimTacGiaActionPerformed(evt);
            }
        });
        txtTimTacGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimTacGiaKeyPressed(evt);
            }
        });
        panelRound4.add(txtTimTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 40));

        btnTimTacGia.setBackground(new java.awt.Color(232, 244, 234));
        btnTimTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/search (1).png"))); // NOI18N
        btnTimTacGia.setBoderColor(new java.awt.Color(232, 244, 234));
        btnTimTacGia.setRadius(10);
        btnTimTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTacGiaActionPerformed(evt);
            }
        });
        panelRound4.add(btnTimTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 40, 40));

        jPanel2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 530));

        jScrollPane3.setViewportView(jPanel1);

        panelRound3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 420));

        tabTacGia.addTab("Tài khoản mượn", panelRound3);

        panelRound5.setBackground(new java.awt.Color(254, 254, 254));
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenDangNhap.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDangNhapKeyPressed(evt);
            }
        });
        panelRound5.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 370, 40));

        lblTenDangNhap.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenDangNhap.setText("Tài khoản mượn");
        panelRound5.add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtTenDangNhap1.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDangNhap1KeyPressed(evt);
            }
        });
        panelRound5.add(txtTenDangNhap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 370, 40));

        lblTenDangNhap1.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenDangNhap1.setText("Mã sách mượn");
        panelRound5.add(lblTenDangNhap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtNgaySinhTacGia.setBackground(new java.awt.Color(222, 247, 227));
        panelRound5.add(txtNgaySinhTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 320, 40));

        lblNgaySinh.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblNgaySinh.setText("Ngày mượn");
        panelRound5.add(lblNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        Calendar.setBackground(new java.awt.Color(201, 235, 201));
        Calendar.setDecorationBackgroundColor(new java.awt.Color(153, 255, 153));
        Calendar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        Calendar.setWeekdayForeground(new java.awt.Color(51, 51, 51));
        Calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CalendarPropertyChange(evt);
            }
        });
        panelRound5.add(Calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, -1));

        btnIconCld1.setBackground(new java.awt.Color(87, 190, 110));
        btnIconCld1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/calendar.png"))); // NOI18N
        btnIconCld1.setAutoscrolls(true);
        btnIconCld1.setBoderColor(new java.awt.Color(204, 204, 204));
        btnIconCld1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIconCld1MouseClicked(evt);
            }
        });
        panelRound5.add(btnIconCld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 50, 40));

        txtTenDangNhap2.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDangNhap2KeyPressed(evt);
            }
        });
        panelRound5.add(txtTenDangNhap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 370, 40));

        lblTenDangNhap2.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenDangNhap2.setText("Tên sách mượn");
        panelRound5.add(lblTenDangNhap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        txtTenDangNhap3.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDangNhap3KeyPressed(evt);
            }
        });
        panelRound5.add(txtTenDangNhap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 370, 40));

        lblTenDangNhap3.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenDangNhap3.setText("Mã mượn sách");
        panelRound5.add(lblTenDangNhap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtTenDangNhap4.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDangNhap4KeyPressed(evt);
            }
        });
        panelRound5.add(txtTenDangNhap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 370, 40));

        lblTenDangNhap4.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenDangNhap4.setText("Mã mượn sách chi tiết");
        panelRound5.add(lblTenDangNhap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        myButton1.setBackground(new java.awt.Color(87, 190, 110));
        myButton1.setBoderColor(new java.awt.Color(87, 190, 110));
        myButton1.setRadius(15);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        panelRound5.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 120, 45));

        myButton2.setBackground(new java.awt.Color(87, 190, 110));
        myButton2.setBoderColor(new java.awt.Color(87, 190, 110));
        myButton2.setRadius(15);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        panelRound5.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 45, 45));

        myButton3.setBackground(new java.awt.Color(255, 102, 102));
        myButton3.setBoderColor(new java.awt.Color(255, 102, 102));
        myButton3.setRadius(15);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        panelRound5.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 45, 45));

        tabTacGia.addTab("Thông tin chi tiết", panelRound5);

        panelRound1.add(tabTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 870, 460));

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(20);
        pnlExit1.setRoundTopRight(20);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExit1MousePressed(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        panelRound1.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTacGiaMouseClicked
        if (evt.getClickCount() == 2) {
            
         
          
        }
    }//GEN-LAST:event_tblTacGiaMouseClicked

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
//        int index = tblTacGia.getSelectedRow();
//        UtilityHelper.last(index, tblTacGia, ListTG);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
//        int index = tblTacGia.getSelectedRow();
//        UtilityHelper.next(index, tblTacGia, ListTG);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
//        int index = tblTacGia.getSelectedRow();
//        UtilityHelper.previous(index, tblTacGia, ListTG);
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
//        int index = tblTacGia.getSelectedRow();
//        UtilityHelper.first(index, tblTacGia);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void tabTacGiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabTacGiaStateChanged
       
    }//GEN-LAST:event_tabTacGiaStateChanged

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExit1MousePressed

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlExit1MousePressed

    private void tblTacGia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTacGia1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTacGia1MouseClicked

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void txtTimTacGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimTacGiaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           
        }
    }//GEN-LAST:event_txtTimTacGiaKeyPressed

    private void btnTimTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTacGiaActionPerformed
     
    }//GEN-LAST:event_btnTimTacGiaActionPerformed

    private void txtTimTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimTacGiaActionPerformed

    private void txtTenDangNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDangNhapKeyPressed
       
    }//GEN-LAST:event_txtTenDangNhapKeyPressed

    private void txtTenDangNhap1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDangNhap1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhap1KeyPressed

    private void CalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CalendarPropertyChange
        txtNgaySinhTacGia.setText(String.valueOf(ShareHelper.formats.format(Calendar.getDate())));
    }//GEN-LAST:event_CalendarPropertyChange

    private void btnIconCld1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIconCld1MouseClicked
        Calendar.setVisible(congTac);
        congTac = !congTac;
    }//GEN-LAST:event_btnIconCld1MouseClicked

    private void txtTenDangNhap2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDangNhap2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhap2KeyPressed

    private void txtTenDangNhap3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDangNhap3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhap3KeyPressed

    private void txtTenDangNhap4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDangNhap4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhap4KeyPressed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerBorrowDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerBorrowDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerBorrowDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerBorrowDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManagerBorrowDiaLog dialog = new ManagerBorrowDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendar;
    private com.ebooks.Compoment.MyButton btnFirst;
    private com.ebooks.Compoment.MyButton btnFirst1;
    private com.ebooks.Compoment.MyButton btnIconCld1;
    private com.ebooks.Compoment.MyButton btnLast;
    private com.ebooks.Compoment.MyButton btnLast1;
    private com.ebooks.Compoment.MyButton btnNext;
    private com.ebooks.Compoment.MyButton btnNext1;
    private com.ebooks.Compoment.MyButton btnPrev;
    private com.ebooks.Compoment.MyButton btnPrev1;
    private com.ebooks.Compoment.MyButton btnTimTacGia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblTenDangNhap1;
    private javax.swing.JLabel lblTenDangNhap2;
    private javax.swing.JLabel lblTenDangNhap3;
    private javax.swing.JLabel lblTenDangNhap4;
    private com.ebooks.Compoment.MyButton myButton1;
    private com.ebooks.Compoment.MyButton myButton2;
    private com.ebooks.Compoment.MyButton myButton3;
    private com.ebooks.Compoment.PanelRound panelRound1;
    private com.ebooks.Compoment.PanelRound panelRound2;
    private com.ebooks.Compoment.PanelRound panelRound3;
    private com.ebooks.Compoment.PanelRound panelRound4;
    private com.ebooks.Compoment.PanelRound panelRound5;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private javax.swing.JTabbedPane tabTacGia;
    private com.ebooks.Compoment.Table tblTacGia;
    private com.ebooks.Compoment.Table tblTacGia1;
    private javax.swing.JTextField txtNgaySinhTacGia;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtTenDangNhap1;
    private javax.swing.JTextField txtTenDangNhap2;
    private javax.swing.JTextField txtTenDangNhap3;
    private javax.swing.JTextField txtTenDangNhap4;
    private com.ebooks.Compoment.SearchText txtTimTacGia;
    // End of variables declaration//GEN-END:variables
}
